apiVersion: batch/v1
kind: CronJob
metadata:
  name: simple-cronjob
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: simple-container
            image: busybox
            command: ["echo", "This is a CronJob running every 5 minutes"]
          restartPolicy: OnFailure
