apiVersion: apps/v1
kind: Deployment
metadata:
  name: ci-cd-app-deployment-config-enabled
  labels:
    app: ci-cd-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ci-cd-app-config-enabled
  template:
    metadata:
      labels:
        app: ci-cd-app-config-enabled
    spec:
      containers:
      - name: ci-cd-app
        image: hangrysingh/python-flask-demo:config-enabled
        command:
          - python
          - with-config-app.py
        ports:
        - containerPort: 5000
        env:
          - name: SECRET_KEY
            valueFrom:
              secretKeyRef:
                key: SECRET_KEY
                name: ci-cd-secrets
          - name: WELCOME_MESSAGE
            valueFrom:
              configMapKeyRef:
                name: ci-cd-configmap
                key: WELCOME_MESSAGE
        # volumeMounts:
        #   - mountPath: /app/data
        #     name: ci-cd-storage
        resources:
          requests:
            cpu: "0.5"
            memory: 1Gi
          limits:
            cpu: "0.5"
            memory: 1Gi
        livenessProbe:
          httpGet:
            path: /k8s
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /k8s
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 20
        startupProbe:
          httpGet:
            path: /k8s
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 20
      # volumes:
      #   - name: ci-cd-storage
      #     persistentVolumeClaim:
      #       claimName: ci-cd-pvc
      imagePullSecrets:
      - name: docker-secrets
