apiVersion: apps/v1
kind: Deployment
metadata:
  name: ci-cd-app-deployment
  labels:
    app: ci-cd-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ci-cd-app
  template:
    metadata:
      labels:
        app: ci-cd-app
    spec:
      containers:
      - name: ci-cd-app
        image: hangrysingh/python-flask-demo:latest
        ports:
        - containerPort: 5000
        # volumeMounts:
        #   - mountPath: /app/data
        #     name: ci-cd-storage
        resources:
          requests:
            cpu: "0.5"
            memory: 1Gi
          limits:
            cpu: "0.5"
            memory: 1Gi
        # livenessProbe:
        #   httpGet:
        #     path: /k8s
        #     port: 5000
        #   initialDelaySeconds: 5
        #   periodSeconds: 20
        # readinessProbe:
        #   httpGet:
        #     path: /k8s
        #     port: 5000
        #   initialDelaySeconds: 5
        #   periodSeconds: 20
        # startupProbe:
        #   httpGet:
        #     path: /k8s
        #     port: 5000
        #   initialDelaySeconds: 5
        #   periodSeconds: 20
      # volumes:
      #   - name: ci-cd-storage
      #     persistentVolumeClaim:
      #       claimName: ci-cd-pvc
      imagePullSecrets:
      - name: docker-secrets
