apiVersion: batch/v1
kind: Job
metadata:
  name: simple-job
spec:
  template:
    spec:
      containers:
      - name: simple-container
        image: busybox
        command: ["echo", "Hello, Kubernetes Job! CKA Class"]
      restartPolicy: Never
  backoffLimit: 4
