apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ci-cd-app--state-deployment
  labels:
    app: ci-cd-app-state
spec:
  serviceName: ci-cd-app-hl-svc
  replicas: 2
  selector:
    matchLabels:
      app: ci-cd-app-state
  template:
    metadata:
      labels:
        app: ci-cd-app-state
    spec:
      containers:
      - name: ci-cd-app
        image: hangrysingh/python-flask-demo:latest
        ports:
        - containerPort: 5000
        # resources:
        #   requests:
        #     cpu: "0.5"
        #     memory: 1Gi
        #   limits:
        #     cpu: "0.5"
        #     memory: 1Gi
        livenessProbe:
          httpGet:
            path: /k8s
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /k8s
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 20
        startupProbe:
          httpGet:
            path: /k8s
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 20
      imagePullSecrets:
      - name: docker-secrets
